### ISSUE TITLE
Test the Model without GUI

### ISSUE THREAD

**Issue by coconut0012** [Quyans/GOI-Hyperplane#3]
Hi, this is a very interesting work.  How do we test the model without GUI?

**Comment by Quyans** [comment]
Hi, thanks for your interest. Since it conbines 2D RES model, we haven't supported  to test the model without GUI yet. If you are using a headless GPU server, you can consider using a remote desktop to test our model.

**Comment by coconut0012** [comment]
Thanks for your suggestion. I will try it!
