### ISSUE TITLE
Train the model using Replica dataset

### ISSUE THREAD

**Issue by coconut0012** [Quyans/GOI-Hyperplane#4]
Hi, I also want to try the model using the Replica dataset.  Could you release the preprocessed Replica dataset or more implementation details about preprocessing it?

Thank you very much!

**Comment by Atrovast** [comment]
Thank you for your interest! Our modified version is derived from [*Semantic-NeRF*](https://github.com/Harry-Zhi/semantic_nerf). We reduced the dataset to approximately 150 images per scene and exported the data into COLMAP format. The [download link](https://drive.google.com/file/d/1n8qf47GFvcWVgKkk0QQnc3VeEVDqxkBr/view) for our processed version has been updated in the README file. For more information, please refer to the README.md file in the dataset.
