### ISSUE TITLE
eval code release

### ISSUE THREAD

**Issue by pz0826** [Quyans/GOI-Hyperplane#5]
Congratulations on your excellent work! I wanted to ask if you plan to release the evaluation code soon, or if there's a way to obtain the predicted binary masks via the GUI.

Thanks for your time!

**Comment by Atrovast** [comment]
Thanks for taking an interest in our research! We have updated the GUI and released the evaluation code. You can refer to [the GUI documentation](https://github.com/Quyans/GOI-Hyperplane/blob/master/gui/gui_doc.md) for instructions on obtaining and saving the binary masks.
